#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

DEV=0
UNIVERSAL=0
INSTALL=0
APP_VERSION=""
for arg in "$@"; do
  case "$arg" in
    --dev)           DEV=1 ;;
    --universal)     UNIVERSAL=1 ;;
    --install)       INSTALL=1 ;;
    --version=*)     APP_VERSION="${arg#--version=}" ;;
    *) echo "Unknown argument: $arg"; exit 1 ;;
  esac
done

if [[ $DEV -eq 1 ]]; then
  APP="PawTermDev.app"
  BUNDLE_ID="com.airoucat.pawterm.dev"
  DISPLAY_NAME="PawTerm Dev"
else
  APP="PawTerm.app"
  BUNDLE_ID="com.airoucat.pawterm"
  DISPLAY_NAME="PawTerm"
fi

if [[ $UNIVERSAL -eq 1 ]]; then
  # Universal Binary: requires full Xcode.app
  ARCH_FLAGS="--arch arm64 --arch x86_64"
else
  ARCH_FLAGS="--arch $(uname -m)"
fi

DEFAULT_CONFIG="$HOME/.config/pawterm/$([ $DEV -eq 1 ] && echo 'config.dev.json' || echo 'config.json')"
cat > Sources/PawTerm/BuildConfig.swift << SWEOF
// Auto-generated by build.sh — do not edit
enum BuildConfig {
    static let defaultConfigPath = "$DEFAULT_CONFIG"
}
SWEOF

echo "Building ${APP}..."
swift build -c release $ARCH_FLAGS

if [[ -d "$APP" ]]; then
  echo "Removing existing ${APP}..."
  rm -rf "$APP"
fi
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# Patch Info.plist with correct bundle ID and display name
python3 - <<PYEOF
import plistlib, pathlib, copy

src = pathlib.Path("Info.plist")
with open(src, "rb") as f:
    pl = plistlib.load(f)

pl["CFBundleIdentifier"] = "$BUNDLE_ID"
pl["CFBundleName"] = "$DISPLAY_NAME"
pl["CFBundleDisplayName"] = "$DISPLAY_NAME"
if "$APP_VERSION":
    pl["CFBundleShortVersionString"] = "$APP_VERSION"

with open("$APP/Contents/Info.plist", "wb") as f:
    plistlib.dump(pl, f)
PYEOF

if [[ $UNIVERSAL -eq 1 ]]; then
  cp .build/apple/Products/Release/PawTerm "$APP/Contents/MacOS/PawTerm"
else
  cp .build/release/PawTerm "$APP/Contents/MacOS/PawTerm"
fi

SIZE=$(du -sh "$APP/Contents/MacOS/PawTerm" | awk '{print $1}')
APP_SIZE=$(du -sh "$APP" | awk '{print $1}')

echo ""
echo "Built ${APP}  (binary: ${SIZE}, total: ${APP_SIZE})"
echo ""

if [[ $INSTALL -eq 1 ]]; then
  # Kill running instance before replacing
  pkill -f "/Applications/${APP}/Contents/MacOS" 2>/dev/null || true
  sleep 1

  if [[ -d "/Applications/${APP}" ]]; then
    echo "Removing existing /Applications/${APP}..."
    rm -rf "/Applications/${APP}"
  fi
  echo "Installing to /Applications/${APP}..."
  mv "${APP}" "/Applications/${APP}"
  xattr -d com.apple.quarantine "/Applications/${APP}" 2>/dev/null || true
  echo "Launching ${APP}..."
  open "/Applications/${APP}"
fi
