#!/usr/bin/env zsh
# Build Mac app. Prompts for version bump unless --dev or CI=true.
#
# Usage:
#   ./scripts/build.sh                 # prod PawTerm.app zip -> dist/
#   ./scripts/build.sh --prod          # prod PawTerm.app zip -> dist/
#   ./scripts/build.sh --dev           # local PawTermDev.app
#   ./scripts/build.sh --dev --install # local PawTermDev.app -> /Applications

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MAC_DIR="$(dirname "$SCRIPT_DIR")"
REPO_ROOT="$(dirname "$MAC_DIR")"
PLIST="$MAC_DIR/Info.plist"
DIST_DIR="$REPO_ROOT/dist"

DEV=0
INSTALL=0
UNIVERSAL=0
for arg in "$@"; do
  case "$arg" in
    --prod) DEV=0 ;;
    --dev) DEV=1 ;;
    --install) INSTALL=1 ;;
    --universal) UNIVERSAL=1 ;;
    *) echo "Unknown argument: $arg" >&2; exit 1 ;;
  esac
done

if [[ $DEV -eq 1 ]]; then
  APP="PawTermDev.app"
  BUNDLE_ID="com.airoucat.pawterm.dev"
  DISPLAY_NAME="PawTerm Dev"
  CONFIG_FILE="config.dev.json"
  DEFAULT_PORT=8765
else
  APP="PawTerm.app"
  BUNDLE_ID="com.airoucat.pawterm"
  DISPLAY_NAME="PawTerm"
  CONFIG_FILE="config.json"
  DEFAULT_PORT=18765
fi

# -------- Read version --------

VERSION=$(/usr/bin/python3 -c "
import plistlib
with open('$PLIST', 'rb') as f: pl = plistlib.load(f)
print(pl.get('CFBundleShortVersionString', '0.0.0'))
")

echo
echo "  current: \033[36m$VERSION\033[0m"
echo "  flavor : \033[36m$([[ $DEV -eq 1 ]] && echo dev || echo prod)\033[0m"
echo "  port   : \033[36m$DEFAULT_PORT\033[0m"

# -------- Bump (prod release only, skip in CI) --------

if [[ $DEV -eq 0 && "${CI:-}" != "true" ]]; then
  IFS='.' read -r MAJOR MINOR PATCH <<<"$VERSION"

  echo
  cat <<MENU
  Choose bump:
    1)  same     $VERSION
    2)  patch    $MAJOR.$MINOR.$((PATCH+1))
    3)  minor    $MAJOR.$((MINOR+1)).0
    4)  major    $((MAJOR+1)).0.0
    q)  quit
MENU

  printf "  → [1-4/q, default=1]: "
  read -r CHOICE
  CHOICE="${CHOICE:-1}"

  case "$CHOICE" in
    1|same)  NEW="$VERSION" ;;
    2|patch) NEW="$MAJOR.$MINOR.$((PATCH+1))" ;;
    3|minor) NEW="$MAJOR.$((MINOR+1)).0" ;;
    4|major) NEW="$((MAJOR+1)).0.0" ;;
    q|quit)  echo "  aborted."; exit 0 ;;
    *)       echo "  invalid choice" >&2; exit 1 ;;
  esac

  if [[ "$NEW" != "$VERSION" ]]; then
    /usr/bin/python3 - <<PY
import plistlib, pathlib
p = pathlib.Path("$PLIST")
with open(p, "rb") as f: pl = plistlib.load(f)
pl["CFBundleShortVersionString"] = "$NEW"
with open(p, "wb") as f: plistlib.dump(pl, f)
PY
    echo "  bumped  → \033[32m$NEW\033[0m"
  fi
  VERSION="$NEW"
fi

echo

# -------- Build --------

cd "$MAC_DIR"

DEFAULT_CONFIG="$HOME/.config/pawterm/$CONFIG_FILE"
cat > Sources/PawTerm/BuildConfig.swift <<SWEOF
// Auto-generated by scripts/build.sh - do not edit
enum BuildConfig {
    static let defaultConfigPath = "$DEFAULT_CONFIG"
    static let defaultServerPort = $DEFAULT_PORT
}
SWEOF

if [[ $UNIVERSAL -eq 1 ]]; then
  ARCH_FLAGS="--arch arm64 --arch x86_64"
else
  ARCH_FLAGS="--arch $(uname -m)"
fi

echo "▶ swift build -c release $ARCH_FLAGS"
swift build -c release $ARCH_FLAGS

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

/usr/bin/python3 - <<PY
import plistlib, pathlib
src = pathlib.Path("$PLIST")
with open(src, "rb") as f:
    pl = plistlib.load(f)
pl["CFBundleIdentifier"] = "$BUNDLE_ID"
pl["CFBundleName"] = "$DISPLAY_NAME"
pl["CFBundleDisplayName"] = "$DISPLAY_NAME"
pl["CFBundleShortVersionString"] = "$VERSION"
with open("$APP/Contents/Info.plist", "wb") as f:
    plistlib.dump(pl, f)
PY

if [[ $UNIVERSAL -eq 1 ]]; then
  /bin/cp .build/apple/Products/Release/PawTerm "$APP/Contents/MacOS/PawTerm"
else
  /bin/cp .build/release/PawTerm "$APP/Contents/MacOS/PawTerm"
fi

SIZE=$(du -sh "$APP/Contents/MacOS/PawTerm" | awk '{print $1}')
APP_SIZE=$(du -sh "$APP" | awk '{print $1}')

echo
echo "Built ${APP}  (binary: ${SIZE}, total: ${APP_SIZE})"

if [[ $INSTALL -eq 1 ]]; then
  pkill -f "/Applications/${APP}/Contents/MacOS" 2>/dev/null || true
  sleep 1

  if [[ -d "/Applications/${APP}" ]]; then
    echo "Removing existing /Applications/${APP}..."
    rm -rf "/Applications/${APP}"
  fi
  echo "Installing to /Applications/${APP}..."
  mv "${APP}" "/Applications/${APP}"
  xattr -d com.apple.quarantine "/Applications/${APP}" 2>/dev/null || true
  echo "Launching ${APP}..."
  open "/Applications/${APP}"
fi

if [[ $DEV -eq 0 ]]; then
  find "$DIST_DIR" -maxdepth 1 -name "PawTerm-*-mac.zip" -delete 2>/dev/null || true
  mkdir -p "$DIST_DIR"
  ditto -c -k --keepParent "$MAC_DIR/PawTerm.app" "$DIST_DIR/PawTerm-${VERSION}-mac.zip"
  echo
  echo "\033[32m✓ build done\033[0m  v$VERSION  →  dist/PawTerm-${VERSION}-mac.zip"
else
  echo
  echo "\033[32m✓ build done\033[0m  v$VERSION"
fi
